#!/bin/bash


sudo sysctl net.mptcp.mptcp_binder_gateways 
sudo sysctl net.mptcp.mptcp_checksum 
sudo sysctl net.mptcp.mptcp_debug 
sudo sysctl net.mptcp.mptcp_enabled 
sudo sysctl net.mptcp.mptcp_path_manager 
sudo sysctl net.mptcp.mptcp_scheduler
sudo sysctl net.mptcp.mptcp_syn_retries 
sudo sysctl net.mptcp.mptcp_version 
sudo sysctl net.ipv4.tcp_available_congestion_control 
sudo sysctl net.ipv4.tcp_allowed_congestion_control
sudo sysctl net.ipv4.tcp_congestion_control
sudo sysctl net.ipv4.tcp_rmem                                                                                                                                                         
sudo sysctl net.ipv4.tcp_wmem                                                                                                                                                         
sudo sysctl net.core.rmem_max                                                                                                                                                         
sudo sysctl net.core.wmem_max
sudo sysctl net.ipv4.tcp_moderate_rcvbuf

echo "Num Subflows:"
echo "Ndiffports"
cat /sys/module/mptcp_ndiffports/parameters/num_subflows
echo "Fullmesh"
cat /sys/module/mptcp_fullmesh/parameters/num_subflows
